import axios from 'axios';
import crypto from 'crypto';
import { BaseIntegrationProvider } from './BaseIntegrationProvider.js';

export class TemuProvider extends BaseIntegrationProvider {
  constructor(options = {}) {
    super('TEMU', 'Temu Open Platform (MMS)', { ...options, connectionMethod: 'token' });
    this.appKey = process.env.TEMU_APP_KEY || '';
    this.appSecret = process.env.TEMU_APP_SECRET || '';
    this.apiBaseUrl = process.env.TEMU_API_URL || 'https://open.temu.com/api/v1';
  }

  isProductionConfigured() {
    return Boolean(this.appKey && this.appSecret);
  }

  getProviderInfo() {
    return {
      code: 'TEMU',
      name: 'Temu Open Platform (MMS)',
      connectionMethod: 'token',
      isProductionConfigured: this.isProductionConfigured(),
      authType: 'TOKEN',
      supportsOAuth: false,
      supportsWebhooks: true,
      supportsProductSync: true,
      supportsOrderSync: true,
      supportsInventorySync: true,
      inventoryDirections: ['wms_to_store', 'store_to_wms', 'manual_only'],
      requiredCredentials: ['TEMU_APP_KEY', 'TEMU_APP_SECRET'],
      requiredFields: [
        { key: 'shopType', label: 'Shop Type', placeholder: 'Select shop type', required: true },
        { key: 'siteCountry', label: 'Site Country', placeholder: 'Select country', required: true },
        { key: 'customName', label: 'Custom Store Name', placeholder: 'e.g. My Temu Semi-Managed Shop', required: true },
        { key: 'token', label: 'Authorization Token', placeholder: 'Paste authorization token from Temu MMS', required: true }
      ],
      supportedShopTypes: [
        'Semi-Managed (Half-Managed)',
        'Full-Managed',
        'Local Seller (EU / US)',
        'Global Cross-Border'
      ],
      supportedRegions: ['US MMS Region', 'European MMS Region', 'Global Cross-Border'],
      supportedSites: {
        'US MMS Region': [
          { id: 'US', label: 'United States (US)' },
          { id: 'CA', label: 'Canada (CA)' }
        ],
        'European MMS Region': [
          { id: 'ES', label: 'Spain Site (ES)' },
          { id: 'DE', label: 'Germany Site (DE)' },
          { id: 'FR', label: 'France Site (FR)' },
          { id: 'IT', label: 'Italy Site (IT)' },
          { id: 'UK', label: 'United Kingdom (UK)' }
        ],
        'Global Cross-Border': [
          { id: 'GLOBAL', label: 'Global Cross-Border Site' }
        ]
      },
      productionRequirements: 'Temu Seller Center (MMS) App Authorization Token generated by the merchant.',
      guideTitle: 'How to authorize a Temu shop to 4Seller?',
      guideSteps: [
        'Step 1: Go to Temu Seller Center (MMS) -> App Management / Authorization Center.',
        'Step 2: Locate the Elvis WMS application and click "Authorize".',
        'Step 3: Grant permissions for catalog, order fulfillment, and inventory synchronization, then copy the generated Authorization Token.',
        'Step 4: Return to this page, select your Shop Type and Site Country, enter your Custom Store Name, paste the Authorization Token, and click Connect.'
      ],
      guideNotes: [
        'Note 1: Temu uses direct token-based authorization. You do not need to enter your Temu merchant password.',
        'Note 2: Ensure you select the correct Shop Type (Semi-Managed vs Full-Managed) matching your Temu Seller Center account.'
      ],
      description: 'Connect your Temu Seller Center (MMS) shop via official Authorization Token to sync catalog, import orders, and manage stock.'
    };
  }

  validateConnectionInput(input = {}) {
    super.validateConnectionInput(input);
    if (!input.token || !input.token.trim()) {
      throw new Error('Authorization Token is required to connect Temu shop');
    }
  }

  /**
   * Token-based store authorization for Temu MMS.
   */
  async connectWithToken({ token, customName, shopType = 'Semi-Managed (Half-Managed)', siteCountry = 'US', isSandbox = false }) {
    if (!token || !token.trim()) {
      throw new Error('Valid Temu Authorization Token is required.');
    }

    const cleanToken = token.trim();
    const isMock = isSandbox || cleanToken.startsWith('tmu_test_') || cleanToken.startsWith('sandbox_');

    if (isMock) {
      return {
        accessToken: cleanToken.startsWith('tmu_test_') ? cleanToken : `tmu_access_token_${crypto.randomBytes(16).toString('hex')}`,
        refreshToken: '',
        tokenExpiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), // 90 days validity
        externalStoreId: `TEMU-${siteCountry}-${Date.now().toString().slice(-4)}`,
        storeName: customName || `Temu ${shopType} (${siteCountry})`,
        storeUrl: 'https://seller.kuajingmaihuo.com',
        scopes: ['item.read', 'item.write', 'order.read', 'inventory.update'],
        metadata: {
          shopType,
          siteCountry,
          sandbox: true
        },
        isSandbox: true
      };
    }

    // Live validation against Temu Open Platform API if production key configured
    if (this.appKey && this.appSecret) {
      try {
        const res = await axios.get(`${this.apiBaseUrl}/seller/profile`, {
          headers: { Authorization: `Bearer ${cleanToken}` }
        });
        const sellerData = res.data?.data || {};
        return {
          accessToken: cleanToken,
          refreshToken: '',
          tokenExpiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
          externalStoreId: String(sellerData.mall_id || sellerData.seller_id || `TEMU-${siteCountry}`),
          storeName: customName || sellerData.mall_name || `Temu ${shopType}`,
          storeUrl: 'https://seller.kuajingmaihuo.com',
          scopes: ['item.read', 'item.write', 'order.read', 'inventory.update'],
          metadata: {
            mallId: sellerData.mall_id,
            shopType,
            siteCountry,
            sandbox: false
          },
          isSandbox: false
        };
      } catch (err) {
        throw new Error(`Temu Token Validation Failed: ${err.response?.data?.message || err.message}`);
      }
    }

    // Direct token connection without live app credentials (store token securely)
    return {
      accessToken: cleanToken,
      refreshToken: '',
      tokenExpiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      externalStoreId: `TEMU-${siteCountry}-${Date.now().toString().slice(-4)}`,
      storeName: customName || `Temu ${shopType} (${siteCountry})`,
      storeUrl: 'https://seller.kuajingmaihuo.com',
      scopes: ['item.read', 'item.write', 'order.read', 'inventory.update'],
      metadata: {
        shopType,
        siteCountry,
        sandbox: false
      },
      isSandbox: false
    };
  }

  async validateConnection(store) {
    const token = store.getAccessToken();
    if (!token) return { isValid: false, error: 'No access token stored.' };
    if (token.startsWith('tmu_access_') || !this.appSecret) {
      return { isValid: true };
    }
    try {
      await axios.get(`${this.apiBaseUrl}/seller/profile`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return { isValid: true };
    } catch (err) {
      return { isValid: false, error: err.response?.data?.message || err.message };
    }
  }

  async fetchProducts(store, options = {}) {
    const token = store.getAccessToken();
    if (token.startsWith('tmu_access_') || !this.appSecret) {
      return [
        {
          externalId: 'tmu-item-201',
          sku: 'TMU-PHONE-STAND-ALU',
          name: 'Aluminum Ergonomic Desk Phone & Tablet Stand (Silver)',
          category: 'Electronics Accessories',
          price: 14.99,
          quantity: 120,
          barcode: '84350020001',
          status: 'active'
        },
        {
          externalId: 'tmu-item-202',
          sku: 'TMU-LED-LIGHTSTRIP-5M',
          name: 'RGB Smart LED Strip Lights 5M USB Powered with Remote',
          category: 'Home & Lighting',
          price: 18.50,
          quantity: 85,
          barcode: '84350020002',
          status: 'active'
        }
      ];
    }

    const res = await axios.get(`${this.apiBaseUrl}/goods/list`, {
      headers: { Authorization: `Bearer ${token}` },
      params: { page: options.page || 1, page_size: options.limit || 50 }
    });

    const items = res.data?.data?.goods_list || [];
    return items.map(item => ({
      externalId: String(item.goods_id),
      sku: item.sku || `TEMU-${item.goods_id}`,
      name: item.goods_name,
      category: item.category_name || 'General',
      price: parseFloat(item.price) || 0,
      quantity: parseInt(item.stock_qty, 10) || 0,
      barcode: item.barcode || '',
      status: item.is_on_sale ? 'active' : 'inactive'
    }));
  }

  async fetchOrders(store, options = {}) {
    const token = store.getAccessToken();
    if (token.startsWith('tmu_access_') || !this.appSecret) {
      return [
        {
          externalOrderId: options.externalOrderId || 'TMU-ORD-882901',
          orderNumber: options.orderNumber || '#TM-882901',
          customerName: 'Mateo Hernandez',
          customerEmail: 'mateo.hernandez@example.es',
          date: new Date('2026-08-26T14:30:00Z'),
          status: 'pending',
          // B2B: Temu Open Platform API does not expose buyer VAT/business fields
          isB2B: false,
          b2bClassificationSource: 'temu_api_no_b2b_field',
          companyName: '',
          vatNumber: '',
          items: [
            { sku: 'TMU-PHONE-STAND-ALU', name: 'Aluminum Ergonomic Desk Phone & Tablet Stand (Silver)', quantity: 2, price: 14.99, total: 29.98 }
          ],
          subtotal: 29.98,
          taxTotal: 6.30,
          grandTotal: 36.28,
          deliveryAddress: {
            street: 'Calle Mayor',
            number: '14',
            city: 'Madrid',
            postcode: '28013',
            region: 'Madrid',
            country: 'Spain'
          }
        }
      ];
    }

    const res = await axios.get(`${this.apiBaseUrl}/orders/list`, {
      headers: { Authorization: `Bearer ${token}` },
      params: { order_status: 'unfulfilled', page: options.page || 1, page_size: options.limit || 50 }
    });

    const orders = res.data?.data?.order_list || [];
    return orders.map(o => ({
      externalOrderId: String(o.order_sn || o.order_id),
      orderNumber: `#TM-${o.order_sn || o.order_id}`,
      customerName: o.receiver_name || 'Temu Customer',
      customerEmail: o.buyer_email || 'customer@temu.com',
      date: new Date(o.create_time * 1000 || Date.now()),
      status: 'pending',
      // B2B: Temu API order object does not include buyer VAT/business registration
      isB2B: false,
      b2bClassificationSource: 'temu_api_no_b2b_field',
      companyName: '',
      vatNumber: '',
      items: (o.item_list || []).map(i => ({
        sku: i.sku || `TEMU-SKU-${i.item_id}`,
        name: i.goods_name,
        quantity: parseInt(i.qty, 10) || 1,
        price: parseFloat(i.unit_price) || 0,
        total: parseFloat(i.total_price) || 0
      })),
      subtotal: parseFloat(o.goods_amount) || 0,
      taxTotal: parseFloat(o.tax_amount) || 0,
      grandTotal: parseFloat(o.pay_amount) || 0,
      deliveryAddress: {
        street: o.receiver_address || '',
        number: '',
        city: o.receiver_city || '',
        postcode: o.receiver_zip || '',
        region: o.receiver_province || '',
        country: o.receiver_country || 'Spain'
      }
    }));
  }

  async updateExternalInventory(store, sku, availableQty) {
    const token = store.getAccessToken();
    if (token.startsWith('tmu_access_') || !this.appSecret) {
      return { success: true, updatedSku: sku, newLevel: availableQty, mode: 'sandbox' };
    }
    await axios.post(`${this.apiBaseUrl}/inventory/update`, {
      sku,
      stock_qty: availableQty
    }, {
      headers: { Authorization: `Bearer ${token}` }
    });
    return { success: true, updatedSku: sku, newLevel: availableQty, mode: 'live' };
  }

  /**
   * Verifies Temu webhook signature.
   *
   * Temu sends an HMAC-SHA256 hex digest over the raw request body.
   * Header: x-temu-signature
   *
   * SECURITY: Rejects all webhooks when no signing secret is configured.
   */
  verifyWebhookSignature(req, secret) {
    if (!secret) {
      console.error('[TemuProvider] Webhook rejected: no signing secret configured for store.');
      return false;
    }
    try {
      const signatureHeader = req.headers['x-temu-signature'];
      if (!signatureHeader) {
        console.error('[TemuProvider] Webhook rejected: missing x-temu-signature header.');
        return false;
      }
      const rawBody = req.rawBody;
      if (!rawBody) {
        console.error('[TemuProvider] Webhook rejected: rawBody not available.');
        return false;
      }
      const expectedSig = crypto
        .createHmac('sha256', secret)
        .update(rawBody)
        .digest('hex');
      const sigBuffer = Buffer.from(signatureHeader.toLowerCase(), 'hex');
      const expectedBuffer = Buffer.from(expectedSig, 'hex');
      if (sigBuffer.length !== expectedBuffer.length) return false;
      return crypto.timingSafeEqual(sigBuffer, expectedBuffer);
    } catch (err) {
      console.error('[TemuProvider] verifyWebhookSignature error:', err.message);
      return false;
    }
  }

  /**
   * Parses Temu webhook payload to standardized event.
   */
  parseWebhookEvent(req) {
    const body = req.body || {};
    return {
      eventId: body.message_id || body.event_id || String(Date.now()),
      topic: body.message_type || body.event_type || 'temu.notification',
      payload: body
    };
  }
}
